fund/urls.py
from django.conf.urls import patterns, include, url
from fund.views import *
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^fund_release/(?P<agency_id>[0-9]+)/$', fundReleaseForm),
    url(r'^monthly_alloc/(?P<agency_id>[0-9]+)/$', monthlyAlloc),
    url(r'^get_budget$', getAllocatedBudget),
    url(r'^view_fund_status$',  getFundStatus),
    url(r'^view_fstat_detail$',  viewFundStatDetails),
    url(r'^running_balances$',  agenciesBalanceSummary),
    url(r'^allotment_releases/(?P<agency_id>[0-9]+)/$',  allotmentReleases),
    url(r'^allotment_balance$',  getAllotmentBal),
    url(r'^del_fund_release$',  delFundRelease),
)

rbmo/urls.py
from django.conf.urls import patterns, include, url
from .views import *
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', home),
                       url(r'^home$', home),
                       url(r'^logout$', logout_user),
                       url(r'^agency/wfp/', include('wfp.urls')),
                       url(r'^agency/fund/', include('fund.urls')),
                       url(r'^agency/', include('agency.urls')),
                       url(r'^history/', include('history_logs.urls')),
                       url(r'^requirements/', include('requirements.urls')),
                       url(r'^main$', index),
                       url(r'^main/home$', main),
                       url(r'^main/users/$', users),
                       url(r'^main/add_edit_user$', addEditUser),
                       url(r'^main/change_status$', changeUserStatus),
                       url(r'^main/agencies$', agencies),
                       url(r'^main/pm_agency$', addEditAgency),
                       url(r'^main/rm_agency/(?P<agency_id>[0-9]+)/?', deleteAgency),
                       url(r'^main/agencies_by_sector$', getAgenciesbySector),
                       url(r'^main/manage_agency_docs/(?P<agency_id>[0-9]+)/$',  manageAgencyDocs),
                       url(r'^main/manage_agency_docs/(?P<agency_id>[0-9]+)/(?P<year>[0-9]{4})/$',  manageAgencyDocs),
                       url(r'^main/submit_monthly_mpfr$',  submitMPFR),
                       url(r'^main/submit_requirements$', saveSubmitReqs),
                       url(r'^main/delete_requirement$', delSubmitReqs),
                       url(r'^main/monthly_reports/(?P<agency_id>[0-9]+)/$', mpfroReports),
                       url(r'^main/monthly_reports_form/(?P<agency_id>[0-9]+)/$', mpfro_form),
                       url(r'^main/submit_quarter_reqs$', submitQuarterReq),
                       url(r'^main/allot_releases$', allot_releases),
                       url(r'^main/yearly_fund$', yearly_fund),
                       url(r'^main/fund_distrib$', fundDistribution),
                       url(r'^main/total_monthly_release$', totalMonthlyReleases),
                       url(r'^main/submit_cos$', submitCOS),
                       url(r'^main/agencies_with_compreqs$', agenciesCompReqList),
                       url(r'^main/agencies_with_increqs$', agenciesIncReqList),
                       url(r'^main/change_password$', changePass),
                       url(r'^main/approved_budget$', approvedBudget),
                       url(r'^main/smca$', smca),
                       url(r'^main/add_performance_report', savePerformanceReport),
                       url(r'^main/display_sub_qreqs', getDisplaySubmittedQReq),
                       url(r'^main/fund_distrib_print', fundDistribPrint),

)

wfp/urls.py
from django.conf.urls import patterns, include, url
from wfp.views import *
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^wfp_form/(?P<agency_id>[0-9]+)/$', wfpForm),
                       url(r'^wfpinfo/(?P<agency_id>[0-9]+)/$', viewWFP),
                       url(r'^wfpdetail$', getWFPData),
                       url(r'^wfp_print$', printWFPData),
                       url(r'^approved_budget$', viewApprovedBudget),
                       url(r'^update_monthly_amount$', updateMonthlyAmount),
                       url(r'^update_activity$', updateActivity),
                       url(r'^delete_perf_target$', delPerfTarget),
                       url(r'^performance_target$', addEditPerfTarget),
                       url(r'^get_performance_acc$', getPerformanceAcc),
                       url(r'^delete_activity$', delActivity),
                       url(r'^co_request/(?P<agency_id>[0-9]+)/$', coRequests),
                       url(r'^co_request_form/(?P<agency_id>[0-9]+)/$', coRequestForm),
                       url(r'^co_request_form/(?P<agency_id>[0-9]+)/(?P<co_id>[0-9]+)/$', coRequestForm),
                       url(r'^del_co_request/(?P<co_id>[0-9]+)', delCoRequest),
                       #new urls
                       url(r'^get/performance/target/$', getPerfTarget),
                       #get Programs jax call
                       url(r'^get/unreportedprograms/$', getUnreportedPrograms),
                       url(r'^get/program/physicaltargets/$', getURLPhysicalTargets),
                       url(r'^get/performance_indicator/(?P<indicator_id>[0-9]+)$', getPerformanceIndicator),
                       url(r'^get/performance_report/(?P<report_id>[0-9]+)$', getPerformanceReport),
                       url(r'^update/performance_report/(?P<report_id>[0-9]+)$', updatePerformanceReport),                       
                       url(r'^update/accomplished_targets$', updateAccTarget),                       
)

fund/forms.py
from django import forms
from rbmo.models  import AllotmentReleases
from django.contrib.auth.models import User
from wfp.forms import YearSelectForm

MONTHS = ((1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), 
          (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'),
          (10, 'October'), (11, 'November'), (12, 'December'))

ALLOCATION = (('PS', 'Personal Services'),
              ('MOOE', 'Maintenance and Other Operating Expenses'),
              ('CO', 'Capital Outlay')
             )  



class MCASearchForm(YearSelectForm):    
    month = forms.ChoiceField(choices=MONTHS,
                              widget=forms.Select(attrs={
                                  'class': 'form-control'
                              }
    ))

    allocation  = forms.ChoiceField(choices=ALLOCATION,
                                    widget=forms.Select(attrs={
                                        'class': 'form-control'
                                    }
    ))



class AllotmentReleaseForm(forms.Form):
    MONTHS = ((1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), 
          (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'),
          (10, 'October'), (11, 'November'), (12, 'December'))
    ada = forms.IntegerField(widget=forms.TextInput(attrs={
                            'class'    : 'form-control',
                            'required' : 'True'
    }))
    
    date_release = forms.DateField(widget=forms.DateInput(attrs={
        'class' : 'form-control',
        'type'  : 'date'
    }))

    allocation = forms.ChoiceField(choices=ALLOCATION,
                                   widget = forms.Select(attrs={
                                       'class' : 'form-control'
                                   })
    )

    month = forms.ChoiceField(choices=MONTHS,
                              widget=forms.Select(attrs={
                                  'class': 'form-control'
                              }
    ))
    amount = forms.DecimalField(widget=forms.TextInput(
        attrs={'class': 'form-control',
               'required': 'True'
        }
    ))


    class Meta:
        model = AllotmentReleases
        fields = ['ada', 'month', 'date_release', 'allocation','amount_release']




wfp/forms.py
from django import forms
from rbmo.models  import WFPData, CoRequest
from helpers.helpers import getYearsChoices


class YearSelectForm(forms.Form):
    year = forms.ChoiceField(choices = getYearsChoices(),
                                    widget = forms.Select(attrs = {
                                        'class' : 'form-control'
                                    }))



class WFPForm(forms.ModelForm):
    PROG = (('General Administration and Support Services', 'General Administration and Support Services'),
            ('Support to Operations', 'Support to Operations'),
            ('Operations', 'Operations'),
    )
    program = forms.ChoiceField(choices=PROG,
                                widget = forms.Select(attrs={
                                    'class': 'form-control'
                                })
    )
    activity = forms.CharField(widget=forms.TextInput(attrs={
        'required' : 'True',
        'class'    : 'form-control'
    }))

    jan = forms.DecimalField(widget=forms.NumberInput(attrs={
        'value' : '0'
    }))

    feb = forms.DecimalField(widget=forms.NumberInput(attrs={
        'value' : '0'
    }))

    mar = forms.DecimalField(widget=forms.NumberInput(attrs={
        'value' : '0'
    }))

    apr = forms.DecimalField(widget=forms.NumberInput(attrs={
        'value' : '0'
    }))

    may = forms.DecimalField(widget=forms.NumberInput(attrs={
        'value' : '0'
    }))

    jun = forms.DecimalField(widget=forms.NumberInput(attrs={
        'value' : '0'
    }))

    jul = forms.DecimalField(widget=forms.NumberInput(attrs={
        'value' : '0'
    }))

    aug = forms.DecimalField(widget=forms.NumberInput(attrs={
        'value' : '0'
    }))

    sept = forms.DecimalField(widget=forms.NumberInput(attrs={
        'value' : '0'
    }))

    oct = forms.DecimalField(widget=forms.NumberInput(attrs={
        'value' : '0'
    }))

    nov = forms.DecimalField(widget=forms.NumberInput(attrs={
        'value' : '0'
    }))

    dec = forms.DecimalField(widget=forms.NumberInput(attrs={
        'value' : '0'
    }))


    class Meta:
        model = WFPData
        fields = ['program','activity', 'jan', 'feb', 'mar', 'apr', 'may', 'jun',
                  'jul', 'aug', 'sept', 'oct', 'nov', 'dec']


class CORequestForm(forms.ModelForm):
    class Meta:
        model = CoRequest
        fields = ['date_received','subject', 'action', 'status', 'remarks']
        widgets = {
            'date_received': forms.DateInput(attrs={
                'type'     : 'date',
                'class'    : 'form-control',
                'required' : 'True',
                'style'    : 'width:200px'
            }),
            'subject' : forms.TextInput(attrs={
                'class'    : 'form-control',
                'required' : 'True'
            }),
            'action'  : forms.TextInput(attrs={
                'class'    : 'form-control',
                'required' : 'True'
            }),
            'status'  : forms.TextInput(attrs={
                'class'    : 'form-control',
                'required' : 'True'
            }),
            'remarks'  : forms.Textarea(attrs={
                'class'    : 'form-control',
                'required' : 'True',
                'rows'     : '5',
                'cols'     : '10'
            })
        }

templates/fund/add_fund_release_success.html
{%extends "./admin/base.html" %}

{% block css %}
{% endblock %}

{%block headerpage%}
<div class="container">
  <h2>{{agency.name}}</h2>
  <hr/>
</div>
{%endblock%}

{% block left-content %}
  {% include "./admin/agency_tabs.html" %}
{% endblock %}

{%block right-content%}
<div class="col-sm-9" style="border-left: 1px solid rgb(204, 204, 204); min-height: 350px">
  <p class="alert alert-success">{{msg}}</p>
  <p>
    <a href="/agency/fund/allotment_releases?agency_id={{agency.id}}" class="btn btn-link">
      <span class="glyphicon glyphicon-arrow-left"></span>
      Back to Allotment Releases
    </a>
    &nbsp;
    <a href="/agency/fund/fund_release?agency_id={{agency.id}}" class="btn btn-link">
      <span class="glyphicon glyphicon-plus-sign"></span>
      Add Another
    </a>

  </p>
</div>
{%endblock%}

templates/fund/allotment_releases.html
{%extends "./main/base.html" %}

{% block css %}
{% endblock %}

{% block left-content %}
  {% include "./main/agency_tabs.html" %}
{% endblock %}

{% block right-content %}
<div class="col-sm-9" style="min-height: 500px; background-color: white; padding-bottom:45px;">
  <h3>{{agency.name}}</h3>
  <hr/>
  <div class="col-sm-12">
    <h4>Allotment Releases</h4>
    <div class="form-inline pull-right">
      <form action="/agency/fund/allotment_releases/{{agency.id}}" method="GET">
	<div class="form-group">
	  {{form.year}}
	</div>
	<div class="form-group">
	  <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-search"></span></button>
	</div>
      </form>
      </br>

    </div>
    {% include "msg_pane.html" %}
    <form class="form-inline">
      <a href="/agency/fund/fund_release/{{agency.id}}/" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus-sign"></span>
          Allotment Release
      </a>
      &nbsp;|&nbsp;
      <a href="javascript:$('#allotment_releases_print').printArea()" class="btn btn-primary">
	<span class="glyphicon glyphicon-print"></span>
	Print
      </a>
    </form>
    <br />
    <table class="table table-condensed table-bordered">
	{%load humanize%}
	<thead>
      	  <tr>
	    <th></th>
	    <th></th>
      	    <th>DATE</th>
      	    <th>ADA NO.</th>
      	    <th>PARTICULARS</th>
      	    <th>PS</th>
      	    <th>MOOE</th>
      	    <th>CO</th>
      	    <th>TOTAL RELEASES</th>
      	    <th>REMAINING BALANCE</th>
      	  </tr>
          <tr>
            <th colspan="5">APPROVED APPROPRIATON</th>
            <th style="text-align:right">{{ wfp_data_PS|intcomma }}</th>
            <th style="text-align:right">{{ wfp_data_MOOE|intcomma }}</th>
            <th style="text-align:right">{{ wfp_data_CO|intcomma }}</th>
            <th></th>
            <th style="text-align:right">{{ remaining_balance|intcomma }}</th>
          </tr>
	</thead>
	<tbody>
      	  <tr style="font-weight: bold;">
      	    <td colspan="5">ALLOTMENT RELEASES</td>
      	    <td></td>
      	    <td></td>
      	    <td></td>
      	    <td></td>
      	    <td></td>
      	</tr>
          {% for releases in allotments%}
	  <tr>
	    <td><a href="/agency/fund/fund_release/{{agency.id}}/?rid={{releases.id}}&action=edit"><span class="glyphicon glyphicon-pencil text-primary"></span></a></td>
	    <td><a href="javascript:confirmDeleteFundRelease('{{releases.id}}', '{{releases.ada_no}}')"><span class="glyphicon glyphicon-remove text-danger"></span></a></td>
	    <td width="60px;">{{ releases.date_release|date:"d M" }}</td>
	    <td>{{ releases.ada_no }}</td>
	    <td>{{ releases.particulars }}</td>
	    
	    {% if releases.allocation.name == 'PS' %}
	    <td style="text-align:right">{{ releases.allocation.amount_release|intcomma }}</td>
	    <td></td>
	    <td></td>
	    {% elif releases.allocation.name == 'MOOE' %}
	    <td></td>
	    <td style="text-align:right">{{ releases.allocation.amount_release|intcomma }}</td>
	    <td></td>
	    {% else %}
	    <td></td>
	    <td></td>
	    <td style="text-align:right">{{ releases.allocation.amount_release|intcomma }}</td>
	    {% endif %}
	    
	    <td style="text-align:right">{{ releases.total_release|intcomma }}</td>
	    <td style="text-align:right">{{ releases.remaining_balance|intcomma }}</td>	
	  </tr>
          {% endfor %}
	</tbody>
	<tfoot>
      	  <tr style="font-weight: bold;">
        	<td colspan="5">TOTAL RELEASES</td>
        	<td style="text-align:right">{{ total_PS|intcomma }}</td>
        	<td style="text-align:right">{{ total_MOOE|intcomma }}</td>
        	<td style="text-align:right">{{ total_CO|intcomma }}</td>
        	<td style="text-align:right">{{ total_release|intcomma }}</td>
        	<td></td>
        </tr>
          <tr  style="font-weight: bold;">
            <td colspan="5">TOTAL BALANCE</td>
            <td style="text-align:right">{{ total_PS_balance|intcomma }}</td>
            <td style="text-align:right">{{ total_MOOE_balance|intcomma }}</td>
            <td style="text-align:right">{{ total_CO_balance|intcomma }}</td>
            <td></td>
            <td style="text-align:right">{{ total_remaining_balance|intcomma }}</td>
          </tr>
	</tfoot>
      </table>
  </div>
</div>

{%include "./fund/allotment_releases_print.html"%}

{% endblock %}
  
{% block scripts %}
<script type="text/javascript">
  function confirmDeleteFundRelease(release_id, ada_no){
     var rs = confirm("Are you sure to delete Allotment Release with ada no. "+ada_no+"?"); 
     if (rs==1){
       window.location = "/agency/fund/del_fund_release?release_id="+release_id;
     }
  }
</script>
{% endblock %}
  

templates/fund/allotment_releases_print.html
<div class="col-sm-12" id="allotment_releases_print" style="display: none">
  <div class="col-sm-12" style="text-align: center">
    <h4>STATUS OF CY{{year}} ALLOTMENT RELEASES</h4>
    <h5>As of {{today}}</h5>
    <h5>(In Pesos)</h5>
  </div>
  
  <div class="col-sm-12">
    <p><b>AGENCY: {{agency.name}}</b></p>
  </div>
  
  <div class="col-sm-12">
    <table class="table-normal" style="font-size: 10px;">
      {%load humanize%}
      <thead>
      	<tr>
      	  <th>DATE</th>
      	  <th>ADA NO.</th>
      	  <th>PARTICULARS</th>
      	  <th>PS</th>
      	  <th>MOOE</th>
      	  <th>CO</th>
      	  <th>TOTAL RELEASES</th>
      	  <th>REMAINING BALANCE</th>
      	</tr>
        <tr>
          <th colspan="3">APPROVED APPROPRIATON</th>
          <th style="text-align:right">{{ wfp_data_PS.total_sum|intcomma }}</th>
          <th style="text-align:right">{{ wfp_data_MOOE.total_sum|intcomma }}</th>
          <th style="text-align:right">{{ wfp_data_CO.total_sum|intcomma }}</th>
          <th></th>
          <th style="text-align:right">{{ remaining_balance|intcomma }}</th>
        </tr>
	</thead>
      <tbody>
      	<tr style="font-weight: bold;">
      	  <td colspan="3">ALLOTMENT RELEASES</td>
      	  <td></td>
      	  <td></td>
      	  <td></td>
      	  <td></td>
      	  <td></td>
      	</tr>
        {% for releases in allotments%}
	<tr>
	  <td>{{ releases.date_release|date:"d M" }}</td>
	  <td>{{ releases.ada_no }}</td>
	  <td>{{ releases.particulars }}</td>
	  
	  {% if releases.allocation.name == 'PS' %}
	  <td style="text-align:right">{{ releases.allocation.amount_release|intcomma }}</td>
	  <td></td>
	  <td></td>
	  {% elif releases.allocation.name == 'MOOE' %}
	  <td></td>
	  <td style="text-align:right">{{ releases.allocation.amount_release|intcomma }}</td>
	  <td></td>
	  {% else %}
	  <td></td>
	  <td></td>
	  <td style="text-align:right">{{ releases.allocation.amount_release|intcomma }}</td>
	  {% endif %}
	  
	  <td style="text-align:right">{{ releases.total_release|intcomma }}</td>
	    <td style="text-align:right">{{ releases.remaining_balance|intcomma }}</td>	
	</tr>
        {% endfor %}
      </tbody>
      <tfoot>
      	<tr style="font-weight: bold;">
          <td colspan="3">TOTAL RELEASES</td>
          <td style="text-align:right">{{ total_PS|intcomma }}</td>
          <td style="text-align:right">{{ total_MOOE|intcomma }}</td>
          <td style="text-align:right">{{ total_CO|intcomma }}</td>
          <td style="text-align:right">{{ total_release|intcomma }}</td>
          <td></td>
        </tr>
        <tr  style="font-weight: bold;">
          <td colspan="3">TOTAL BALANCE</td>
          <td style="text-align:right">{{ total_PS_balance|intcomma }}</td>
          <td style="text-align:right">{{ total_MOOE_balance|intcomma }}</td>
          <td style="text-align:right">{{ total_CO_balance|intcomma }}</td>
          <td></td>
          <td style="text-align:right">{{ total_remaining_balance|intcomma }}</td>
        </tr>
      </tfoot>
    </table>
    <div class="col-sm-12">
      <span style="position: absolute;left: 10px; top: 20px;width: 250px;">
	<strong>Processed by:</br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{user.get_full_name}}<strong>
      </span>

      <span style="position: absolute;left: 70%; top: 20px;width: 30%;">
	<strong>Validated by:</strong></br>&nbsp;&nbsp;&nbsp;&nbsp;___________________
	</br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Budget Specialist
      </span>
    </div>
  </div>
</div>

templates/fund/compliance_editor.html
<!-- Modal -->
<div class="modal" id="complianceModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Notice of Compliance</h4>
      </div>
      <form action="javascript:printNOC()" class="form-horizontal" >
	{%load humanize%}
	<div class="modal-body">
	  <div class="form-group">
	    <label class="col-sm-2">To: </label>
	    <div class="col-sm-10">
	      <p class="form-control-static">{{agency.name}}</p>
	    </div>
	  </div>
	  <div class="form-group">
	    <textarea class="widgEditor nothing" id="content" name="content"><p>Please be informed that upon evaluation of your Agency/Office compliance to the memo 173, which reiterates the regular submission as regards by the Regional Governor, the following marked documents are yet to be received by this office.
    <ul>
      {% for q_req in monthly_alloc_stat.quarter_reqs %}
      <li>{{q_req.name}}</li>
      {% endfor %}
    </ul>
    </br>
    May we remind you of the submission of the above marked documents to facilitate the release of your office monthly cash allocation.</br>
    If submission has already been made, please disregard this notice.</br>
    Thank you for your usual cooperation.

    </p></textarea>
	  </div>
	  <div class="form-group">
	    <label class="col-sm-3">
	      Executive Director
	    </label>
	    <div class="col-sm-9">
	      <input type="text" id="oic" name="oic" class="form-control" placeholder="Executive Director" required>
	    </div>
	  </div>
	</div>
	<div class="modal-footer">
          <button type="button" id="pi_close_modal" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Print</button>
	</div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/fund/compliance_note.html
<div class="col-sm-12" style="display: none" id="com_note">
  <div>
    <center><u><h3>NOTICE OF COMPLIANCE</h3></u></center>
  </div>
  </br>
  <div class="col-sm-12">
    <p>May 5, 2014</p>
  </div>
  </br></br>
  <div class="col-sm-12">
    <b><u>To:&nbsp;{{agency.name}}</u></b>
  </div>
  </br></br>
  <div class="col-sm-12" id="compliance_content">
  </div>
  </br></br>
  <div class="col-sm-12">
    <p>
      <b><span id="oic_letter"></span></b></br>
      Executive Director, RBMO
    </p>
  </div>
</div>

templates/fund/fund_request_form.html
{%extends "./admin/base.html" %}

{% block css %}
<script type="text/javascript">
  $().ready(function(){
  getAllocBudget();    
  });
</script>
{% endblock %}

{% block left-content %}
  {% include "./admin/agency_tabs.html" %}
{% endblock %}

{% block right-content %}
<div class="col-sm-9">
  <h2>{{agency.name}}</h2>
  <hr/>
  <div class="col-sm-12"><!---style="background-color: rgba(204,204,204,.4)"-->
    <h3>Fund Release Form</h3>
    {% include "msg_pane.html" %}
    <form action="/agency/fund/fund_request" role="form" class="form-horizontal" method="POST" onsubmit="return checkFundAmountRelease()">{% csrf_token %}
      <input type="hidden" id="agency_id" name="agency_id" value="{{agency.id}}">
      <div class="form-group">
	<label class="col-sm-3">Year</label>
	<div class="col-sm-9">
	  <input type="hidden" id="id_year" name="year" value="{{year}}">
	  <span style="font-size:20px">{{year}}</span>
	</div>
      </div>

      <div class="form-group">
	<label class="col-sm-3">Allocation</label>
	<div class="col-sm-9">
	  <select name="allocation" id="id_allocation" class="form-control">
	    {% for allocation in allocations %}
	    <option value="{{allocation.id}}">{{allocation.name}}</option>
	    {% endfor %}
	  </select>
	</div>
      </div>

      <div class="form-group">
	<label class="col-sm-3">Allocated Month</label>
	<div class="col-sm-9">
	  {{form.month}}
	</div>
      </div>

      <div class="form-group">
	<label class="col-sm-3">Allocated Budget</label>
	<div class="col-sm-9">
	  <span style="font-size: 18px;" id="budget">0.00</span>
	</div>
      </div>

      <div class="form-group">
	<label class="col-sm-3">Remaining Balance</label>
	<div class="col-sm-9">
	  <span style="font-size: 18px;" id="balance">0.00</span>
	</div>
      </div>
      
      <hr/>
      <div class="form-group">
	<div id="note"></div>
	<label class="col-sm-3">Amount Release</label>
	<div class="col-sm-9">
	  {{form.amount}}
	</div>
      </div>

      <div class="form-group">
	<div class="col-sm-9 col-sm-offset-3">
	  <button type="submit" id="id_submit" class="btn btn-success">
	    Save Fund Release
	  </button>
	</div>
      </div>
      
    </form>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="/static/js/fund_ajax.js"></script>
{% endblock %}


templates/fund/fund_stat_details.html
<h4>{{allocation}} - Fund Status Details</h4>
{% if fund_stat_details %}
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Release Date</th>
      <th>Particulars</th>
      <th  style="text-align: right">Released</th>
      <th  style="text-align: right">Remaining Balance</th>
    </tr>
  </thead>
  <tbody>
    <tr
      <td></td><td></td><td></td><td></td>    
      <td class="decimal">{{total}}</td>
    </tr>
    {% for detail in fund_stat_details%}
    <tr>
      <td>{{detail.release_date}}</td>
      <td>{{detail.activity}}</td>
      <td style="text-align: right">{{detail.release_amount}}</td>
      <td style="text-align: right">{{detail.balance}}</td>
    </tr>
    {% endfor %}
  </tbody>
  </table>
{% else %}
<div class="alert alert-info">
  Currently No Release Transaction
</div>
{% endif %}

templates/fund/notice_of_allocation.html
<div class="col-sm-12" style="display: none" id="trans_note">
  {%load humanize%}
  <div class="col-sm-12">
    <center><u><h3>NOTICE</h3></u></center>
  </div>
  </br>
  <div class="col-sm-12">
    <p>{{cur_date}}</p>
  </div>
  </br>
  <div class="col-sm-12">
    <b>To: {{agency.name}}</b>
  </div>
  </br>
  <div class="col-sm-12" id="content_letter">
  </div>
  </br></br>
  <div class="col-sm-12">
    <p>
      <b><span id="oic_letter"></span></b></br>
      Executive Director, RBMO
    </p>
  </div>
</div>